spring:
  application:
    name: medimitra-backend
  
  # Database Configuration - Neon PostgreSQL
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-muddy-math-a1e2rmtd-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_DfaC31PJjLNq}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JDBC Configuration
  jdbc:
    template:
      query-timeout: 30
  
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Database Initialization - disabled to prevent conflicts
  sql:
    init:
      mode: never
  
  # Security Configuration
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration removed - using NextAuth.js for authentication

# CORS Configuration
cors:
  allowed-origins: "http://localhost:3000,http://localhost:3001,http://localhost:3002"
  allowed-origin-patterns: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true
# OpenRouter AI Configuration
openrouter:
  api:
    key: ${OPENROUTER_API_KEY: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}
    url: ${OPENROUTER_API_URL:https://openrouter.ai/api/v1/chat/completions}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Appwrite Configuration for File Storage
appwrite:
  endpoint: ${APPWRITE_ENDPOINT:https://cloud.appwrite.io/v1}
  project: ${APPWRITE_PROJECT_ID:68c307fe002f136b2920}
  api-key: ${APPWRITE_API_KEY:standard_ad2113f7b35914997ec2b8e0caf1a1b2f26347ddc5faacff1027aed2663761ab3458461af166b04dc8903e5acd52b3f12f2e89c65a6dcc59c9e7d8daaa65932379cde39b127b4cf33a08d715a25077540aca41db257766ef32fde68b3d7e6474ea7b022b2968830ac4a92f68919ad8937ad41afb6e784911d93ef56752bdd0f8}
  bucket-id: ${APPWRITE_BUCKET_ID:medimitra-files}

# Logging Configuration
logging:
  level:
    com.medimitra: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management and Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Application specific properties
app:
  name: MediMitra Healthcare System
  version: 1.0.0
  description: Comprehensive Healthcare Management Platform
