spring:
  application:
    name: medimitra-backend
  
  # Production Database Configuration
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  
  # Production JDBC Configuration
  jdbc:
    template:
      query-timeout: 30

# Production Server Configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  error:
    include-message: never
    include-stacktrace: never

# Production JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

# Production CORS Configuration
cors:
  allowed-origins: ${CORS_ORIGINS}
  allowed-methods: ${CORS_METHODS:GET,POST,PUT,DELETE,OPTIONS}
  allowed-headers: ${CORS_HEADERS:*}
  allow-credentials: ${CORS_CREDENTIALS:true}

# Production Logging Configuration
logging:
  level:
    com.medimitra: INFO
    org.springframework.jdbc: WARN
    org.springframework.security: WARN
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/medimitra/application.log

# Production Management and Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
  server:
    port: 9090

# Production Application Properties
app:
  name: MediMitra Healthcare System
  version: 1.0.0
  description: Production Healthcare Management Platform

